version: '3.3'

services:
  template:
    restart: always
    image: template
    container_name: template
    build: .
    volumes:
          - /opt/template/logs:/opt/template/logs
    ports:
      - 8081:8081
    depends_on:
      - mongodb_docker
    networks:
      - localmongonetwork
  mongodb_docker:
    image: mongo:latest
    container_name: mongo_db_image2
    volumes:
      - /devel/mongodata:/opt/mongodata
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    networks:
      - localmongonetwork
networks:
  localmongonetwork:
    driver: bridge
